modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Clan328/RestorationStone/issues"

[[mods]]
modId="restorationstone"
version="1.0.0"
displayName="Restoration Stone"
displayURL="https://github.com/Clan328/RestorationStone"
logoFile="logo.png"
credits="Thanks to Malcolm Riley for the Restoration Stone's texture"
authors="aTechnoloGeek"
description='''
Adds an item that repairs any tool, weapon or armor and resets its repair cost on an anvil.
'''

[[dependencies.restorationstone]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.restorationstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
